(setq gc-cons-threshold 5242880)
(column-number-mode t)
(setq make-backup-files nil)
(blink-cursor-mode nil)
(menu-bar-mode 0)
(setq inhibit-startup-message t)
(setq fill-collum 80)
(setq visible-bell t)
(transient-mark-mode t)
(show-paren-mode t)
(setq show-paren-style 'mixed)
(setq truncate-partial-width-windows nil)

(set-language-environment "Japanese")
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-buffer-file-coding-system 'utf-8)
(setq default-buffer-file-coding-system 'utf-8)
(prefer-coding-system 'utf-8-unix)

(load-theme 'tango-dark t)
